


export const CHANGE_CATEGORY: 'CHANGE_CATEGORY' = 'CHANGE_CATEGORY';

export const ADD_TO_ORDER: 'ADD_TO_ORDER' = 'ADD_TO_ORDER';
export const DELETE_FROM_ORDER: 'DELETE_FROM_ORDER' = 'DELETE_FROM_ORDER';
export const INCREASE_ITEM_ORDER: 'INCREASE_ITEM_ORDER' = 'INCREASE_ITEM_ORDER';
export const DECREASE_ITEM_ORDER: 'DECREASE_ITEM_ORDER' = 'DECREASE_ITEM_ORDER';


